### ISSUE TITLE
what are the paper list urls?

### ISSUE THREAD

**Issue by neverX2017** [yang-guangliang/big4_bib#1]
Can you tell me what are the paper list urls ? Thanks.
`        PAPER_LIST = sys.argv[1]
`

**Comment by yang-guangliang** [comment]
No, I don't have local copy or urls of the paper lists.
When adding new papers, I just somehow manually generate the paper list of a specific conference. 
I didn't find a good and automatic way to do that. This is quite annoying. 
I can update the list this August.

**Comment by neverX2017** [comment]
Got it, thank you.
